<scriptConfig name="VV_1" script="VV">
  <params>
    <param name="eut.p_min" type="float">0.0</param>
    <param name="gridsim.opal.phases" type="int">3</param>
    <param name="gridsim.opal.vout_scale" type="string">3.0,3.0,3.0</param>
    <param name="vv.test_1_t_r" type="float">5.0</param>
    <param name="eut.startup_time" type="int">10</param>
    <param name="der.Opal.sec_crtl_frz_time" type="string">10.0</param>
    <param name="gridsim.opal.vin_scale" type="string">20.0,20.0,20.0</param>
    <param name="pvsim.Opal.temp" type="float">25.0</param>
    <param name="gridsim.opal.f_min" type="float">45.0</param>
    <param name="eut.f_min" type="float">56.0</param>
    <param name="eut.f_nom" type="float">60.0</param>
    <param name="gridsim.opal.freq" type="float">60.0</param>
    <param name="eut.f_max" type="float">66.0</param>
    <param name="gridsim.opal.f_max" type="float">70.0</param>
    <param name="vv.vref" type="string">100%</param>
    <param name="eut.v_low" type="float">105.6</param>
    <param name="eut.v_nom" type="float">120.0</param>
    <param name="gridsim.opal.v_nom" type="float">120.0</param>
    <param name="das.opal.sample_interval" type="int">125</param>
    <param name="eut.v_high" type="float">132.0</param>
    <param name="gridsim.opal.v_max" type="float">132.0</param>
    <param name="eut.v_in_nom" type="int">400</param>
    <param name="pvsim.Opal.irr" type="float">1000.0</param>
    <param name="eut.var_rated" type="float">2200.0</param>
    <param name="eut.s_rated" type="float">5000.0</param>
    <param name="eut.p_rated" type="float">5000.0</param>
    <param name="gridsim.opal.cin_scale" type="string">-3.32567,-3.33400,-3.327</param>
    <param name="vv.irr" type="string">All</param>
    <param name="das.opal.wfm_dir" type="string">C:\OPAL-RT\CANMETENERGY_WORKSPACE\SIL_1547\models\IEEE_1547_Simulated_Test_Bench\ieee_1547_simulated_test_bench_sm_source\OpREDHAWKtarget</param>
    <param name="das.opal.data_name" type="string">Data.mat</param>
    <param name="vv.test_2" type="string">Disabled</param>
    <param name="vv.test_3" type="string">Disabled</param>
    <param name="UL1741PP.UL1741_enable" type="string">Disabled</param>
    <param name="eut.imbalance_resp" type="string">EUT response to the average of the three-phase effective (RMS)</param>
    <param name="vv.test_1" type="string">Enabled</param>
    <param name="gridsim.auto_config" type="string">Enabled</param>
    <param name="das.opal.rtp.rtp_enable" type="string">Enabled</param>
    <param name="das.opal.wfm_chan_list" type="string">IEEE1547_VRT</param>
    <param name="hil.opal.rt_lab_model" type="string">IEEE_1547_Simulated_Test_Bench</param>
    <param name="hil.opal.hil_config_compile" type="string">No</param>
    <param name="hil.opal.hil_config_stop_sim" type="string">No</param>
    <param name="hil.opal.hil_config_execute" type="string">No</param>
    <param name="vv.mode" type="string">Normal</param>
    <param name="das.opal.rtp.realtime_plotting_edit" type="string">OnRtp</param>
    <param name="der.mode" type="string">Opal</param>
    <param name="gridsim.mode" type="string">Opal</param>
    <param name="pvsim.mode" type="string">Opal</param>
    <param name="das.mode" type="string">Opal</param>
    <param name="hil.mode" type="string">Opal-RT</param>
    <param name="das.opal.map" type="string">Opal_Fast_1547</param>
    <param name="hil.opal.target_name" type="string">RTServer</param>
    <param name="hil.opal.project_dir" type="string">SIL_1547</param>
    <param name="hil.opal.rt_mode" type="string">Software</param>
    <param name="eut.phases" type="string">Three phase</param>
    <param name="hil.opal.hil_config" type="string">True</param>
    <param name="hil.opal.hil_config_open" type="string">Yes</param>
    <param name="hil.opal.hil_config_load" type="string">Yes</param>
  </params>
</scriptConfig>
